version: '2'

services:
  lemp-for-azure:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
#      - ./../../../../www/sample:/var/www/html
      - ./../../../../www/jti/services.chazapp.co:/var/www/html
    ports:
      - 8088:8080

